import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import NavBar from "@components/MainPage/NavBar";

import theme from "./themes";
import { CssBaseline, ThemeProvider } from "@mui/material";
import Providers from "@/components/MainPage/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <html lang="en">
        <body>
        <Providers>
        <NavBar/>
        <AppRouterCacheProvider>
          {children}
        </AppRouterCacheProvider>
        </Providers>
        </body>
      </html>
    </ThemeProvider>
  );
}
